// <auto-generated />
using System;
using LenninSegura2020_0313FP.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LenninSegura2020_0313FP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231205002807_Lenninsegura20200313sec")]
    partial class Lenninsegura20200313sec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.AnoEscolar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("anoEscolar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK__AnoEscol__3214EC27CF008608");

                    b.ToTable("AnoEscolar");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Asignatura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Asignatura1")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Asignatura");

                    b.Property<string>("CargaHoraria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("maestroID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Asignatu__3214EC276F5D9982");

                    b.HasIndex("maestroID");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Curso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cursos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("anoescolarID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Cursos__3214EC2716FDD162");

                    b.HasIndex("anoescolarID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Estudiante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direcion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("NIE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID")
                        .HasName("PK__Estudian__3214EC2722E034F9");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<DateTime>("Fecha_Inscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Limite")
                        .HasColumnType("datetime2");

                    b.Property<int?>("cursoID")
                        .HasColumnType("int");

                    b.Property<int?>("estudianteID")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("cursoID");

                    b.HasIndex("estudianteID");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Maestro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CursoID")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Maestros__3214EC27B025D078");

                    b.HasIndex("CursoID");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Asignatura", b =>
                {
                    b.HasOne("LenninSegura2020_0313FP.Models.Maestro", "maestro")
                        .WithMany("AsignaturaList")
                        .HasForeignKey("maestroID");

                    b.Navigation("maestro");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Curso", b =>
                {
                    b.HasOne("LenninSegura2020_0313FP.Models.AnoEscolar", "anoEscolar")
                        .WithMany("cursos")
                        .HasForeignKey("anoescolarID");

                    b.Navigation("anoEscolar");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Inscripcion", b =>
                {
                    b.HasOne("LenninSegura2020_0313FP.Models.Curso", null)
                        .WithMany("inscripciones")
                        .HasForeignKey("cursoID");

                    b.HasOne("LenninSegura2020_0313FP.Models.Estudiante", "estudiante")
                        .WithMany("inscripciones")
                        .HasForeignKey("estudianteID");

                    b.Navigation("estudiante");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Maestro", b =>
                {
                    b.HasOne("LenninSegura2020_0313FP.Models.Curso", null)
                        .WithMany("maestros")
                        .HasForeignKey("CursoID");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.AnoEscolar", b =>
                {
                    b.Navigation("cursos");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Curso", b =>
                {
                    b.Navigation("inscripciones");

                    b.Navigation("maestros");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Estudiante", b =>
                {
                    b.Navigation("inscripciones");
                });

            modelBuilder.Entity("LenninSegura2020_0313FP.Models.Maestro", b =>
                {
                    b.Navigation("AsignaturaList");
                });
#pragma warning restore 612, 618
        }
    }
}
